version: "3.5"

services:
  npm:
    image: node:18
    volumes:
      - .:/app
    working_dir: /app
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: "localhost,127.0.0.1,"
    entrypoint: [ "npm" ]
    networks:
      - bib-frontend-network

  build:
    image: node:18
    volumes:
      - .:/app
    working_dir: /app
    environment:
      NODE_ENV: production
      VITE_BIBAPI_HOST: ${BIBAPI_HOST}

    command: npm run build --production
    networks:
      - bib-frontend-network

networks:
  bib-frontend-network:
    external: true
