server:
    image: vsregistry.intra.inist.fr:5000/bibadmin:${bibadmin_version}
    environment:
        NODE_ENV: production
    working_dir: /public
    restart: always
    ports:
        - 3010:8080
