version: "3.5"

services:
  bibcnrs-admin:
    container_name: bibcnrs-admin
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/admin:${BIBADMIN_VERSION}
    build:
      context: .
      args:
        BIBAPI_HOST: ${BIBAPI_HOST}
        SOURCE_MAP: ${SOURCE_MAP}
    ports:
      - "8081:8081"
    networks:
      bib-frontend-network:

networks:
  bib-frontend-network:
    external: true
