version: "3.5"

services:
  devserver:
    image: node:18
    volumes:
          - .:/app
          - ./public:/public
    working_dir: /app
    environment:
      NODE_ENV: development
      VITE_BIBAPI_HOST: ${BIBAPI_HOST}
      PORT: 3011
    ports:
      - "3011:3011"
    command: npm start
    networks:
      - bibfrontend

networks:
  bibfrontend:
    external: true
      

