version: "3.5"

services:
  npm:
    image: node:18
    volumes:
      - .:/app
    working_dir: /app
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: "localhost,127.0.0.1,"
    entrypoint: ["npm"]
    networks:
      - bibfrontend
  build:
    image: node:18
    volumes:
      - .:/app
    working_dir: /app
    environment:
      NODE_ENV: production
      REACT_APP_BIBAPI_HOST: ${REACT_APP_BIBAPI_HOST}
      VITE_REACT_APP_BIBAPI_HOST: ${REACT_APP_BIBAPI_HOST}

    command: npm run build --production
    networks:
      - bibfrontend
      
networks:
  bibfrontend:
    external: true
