node:
  image: node:4.1.2
  volumes:
    - .:/app
  environment:
    NODE_ENV: ${NODE_ENV}
  working_dir: /app

npm:
  extends:
    file: ./docker-compose.base.yml
    service: node
  environment:
    http_proxy: ${http_proxy}
    https_proxy: ${https_proxy}
    no_proxy: "localhost,127.0.0.1,"
  entrypoint: ['npm']

server:
  image: cannin/nodejs-http-server
  volumes:
    - ./public:/public
  working_dir: /public
  ports:
    - 3001:8080

build:
  extends:
    file: ./docker-compose.base.yml
    service: node
  command: node node_modules/webpack/bin/webpack.js -p
