
npm:
  image: node:4.1.2
  volumes:
    - .:/app
  environment:
    NODE_ENV: ${NODE_ENV}
    http_proxy: ${http_proxy}
    https_proxy: ${https_proxy}
    no_proxy: "localhost,127.0.0.1,"
  working_dir: /app
  entrypoint: ['npm']

server:
  image: cannin/nodejs-http-server
  volumes:
    - ./public:/public
  working_dir: /public
  ports:
    - 3001:8080
