version: "3.8"

services:
  bibadmin-srv:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/bibadmin:${bibadmin_version}
    environment:
      NODE_ENV: production
    working_dir: /public
    restart: always
    networks:
      - bibfrontend

networks:
  bibfrontend:
    external: true
